version: 2
jobs:
  build:
    docker:
      - image: node:16.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Test
          command: |
            npm install
            npm test
